apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    EXTERNAL_DOMAIN: ENC[AES256_GCM,data:0VEHOUQE5FTbACtfvA==,iv:8+8zEUW70b0y6ZgygOrhL5dKEO+xSxpt2yZUyhGiLxc=,tag:zpQK7CH1PZE3NJdXpFwkhg==,type:str]
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:v+ejccJP+QB4iGG/G1jQNMrrEWhYmw==,iv:ApPy6jx+yPk8A/zx3HK14vgWEMQDL5w5/12pnoNtlqA=,tag:n0PJKbL20cYQRFeONx7jZA==,type:str]
    PROFESSIONAL_DOMAIN: ENC[AES256_GCM,data:w0+cllTMmWRVmv/Bog==,iv:ETdGjc/pcU+WrRYOwtSVG4kdHx+RkRLg6ODK2iAOOag=,tag:VShT8SfX1Omv/E108FelyA==,type:str]
    SECRET_SENDGRID_USER_SMTP_RELAY: ENC[AES256_GCM,data:ILiBQzxlDwk=,iv:BXYkO5X8/gShyhObxQ+t9FgN2LnjEUvcBF1hfy7wSTY=,tag:1FUPEGRowCcecrXd0fGwNQ==,type:str]
    SECRET_SENDGRID_APIKEY_SMTP_RELAY: ENC[AES256_GCM,data:A5UeFLsq4TY+aMMskgYKn056M0OQ08U8gqx/Nj2MxmTbMOplAXOLIbykWa18vr3cbU6ccz6rDcsbVjIJX6TDb4X4AxVS,iv:4MtzltFMAr4aVkK0OxfmmJE+KqK+wDBf6B0ecBf9M4o=,tag:EKpL+x7z23E+hmCpZwne0A==,type:str]
    EMAIL: ENC[AES256_GCM,data:CZkwNv1DEvk2XrYQkjDnH0TjXkQd4w==,iv:O7ro33OGRBCh50cBk3pbhXF1goTMPYTYurIwMwE92os=,tag:f3yOqtl3HA16EDuG6VUGgg==,type:str]
    SECRET_MAXMIND_ACCOUNT_ID: ENC[AES256_GCM,data:+LujP1eV,iv:IHjPtvVzcrpbzTZdy5iyxgjKV+KycIH5CqVJMRDS+Wg=,tag:10hjc1E6e19vYE+a9YP0UQ==,type:str]
    SECRET_MAXMIND_LICENSE_KEY: ENC[AES256_GCM,data:odPe9Qt/FEj7BgSx9coraUM6Pofki+lbOi8CRRCsSJ/BkjYtghHOYw==,iv:pg+nxYjaWQq0vujthE3Ah0bPEkEl2a3rgD++e8n5nGI=,tag:q25JC5Im2vXxFKuikOsM/w==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/moonlit-watch-362206/locations/global/keyRings/davishaus-keyring/cryptoKeys/sops
          created_at: "2023-05-23T02:33:14Z"
          enc: CiQA3rJLN+7Vlrs4hVvkzX9pwanhvjVkQNB1EEzjudJ4lyRWbncSSADC/xGZOmZMqpX6py0idLk+sKa9wD8wuK55EsN5gLRDnxMivTG4UHwXlrN38Oiu8wR1yQGOgNIzCs7UGL9YzWGyNtn4A2oSCw==
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jhlwc2kz4rm95t7hfvrj0mhdg7fwmepj90ap5y26ypxf808xmv8qmhnla5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVXBubVNMaTQrUE0xbGgz
            R1ZqS05UVkhIcEtWNlRIWGFzWjhmelZEVGlFCmpNeTloYXo0Q2MxUy9CdmdpcCtO
            Vjh6MlBLK0lRZStlbVVuV0RZSVljSVUKLS0tIG9jd1ZSam5wNlQ1K3ZsWnpEOTRI
            N3lzaTlLYWJzZGcxOW00VHhDd2d0NUEKuNmnvc0jfrml7qT/NrYLoRL72N2HYOPJ
            e6jGZCCyg+xW3pY4Q/+g23sqfRfOx1rq9sgcTITKPOfU1GooOldiEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-15T22:26:20Z"
    mac: ENC[AES256_GCM,data:a9KuVlLaYvoeaiI4lCWyiXQX9TDAyM9ZZyWLqsEjVSIJg7CL0tkfaNq84Md4aWNINRj9f+7KMcUZEpZXzzGd1yLr/g+pzUkiTdzkBQ0uwTK0IDyoxgrqwO91xDvAjXExEnLnZq/704//f4YA5NOY+jO95ReBV/TBiyt9LWfatm4=,iv:GSPQZa7KQCXbNckn+bzjPadBHbJK4GNYffL2BG43C3w=,tag:jECHBcknTJ4zBrf2Z6KVBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
