apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: datastore
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: security
stringData:
    AWS_SECRET_ACCESS_KEY_ID: ENC[AES256_GCM,data:Iaw0Rw==,iv:2zJbCj5PFtja2GNKSYldrp3m2ri01Fd8KMjjtPuaqDc=,tag:AqHRVGWJoyyMHPgXg6D4pg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Wm49dClSmslB2jGMkQRkUg8JkdilnWUrnHvE7143+oZYL32kAQ5UGg==,iv:p7mWuTwQGV2Qj7xfR1rM8Gogb3CISzX/PnWchv9S3cg=,tag:UTl2WpYcfYvYrlAPg2NjnA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/moonlit-watch-362206/locations/global/keyRings/davishaus-keyring/cryptoKeys/sops
          created_at: "2023-06-15T21:16:46Z"
          enc: CiQA3rJLN6yaOwUgzdGqvnZPOyCs080jgMrkd0UamTKxsFS811wSSADC/xGZxa73jdT8yHR/4QB4bwPQ9f0HR78tLLB9CnY+gRv0WYXxDjKaVlZcWXGJas7/wpV+ljiLXlEL1W8AmWTzGT80Fwrtlg==
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jhlwc2kz4rm95t7hfvrj0mhdg7fwmepj90ap5y26ypxf808xmv8qmhnla5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4eGJ0cjZXQUIrem44V1pN
            VHVzYUVuc0gyL2lvZDQzY0lLOWpGY001Y1VRCmVVeXlUMUVabllReFVZQnI5SVc3
            NHhwaURnSVczTU5wQ2VLaThCdDdkd1EKLS0tIHdLNW1OdUR0UDFKcGg2RS9VckRa
            cnZrWXVpc09GeGpkSnA1Z1oyZHpwb1kKydse0GmC+KIG8LTn+eWioFu+tng1F4eS
            k6Ku6JtkhlNSnB6T409p4EtpMcIOegAv6ZVUK8QoLgXsF59qIwDptg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-18T17:29:27Z"
    mac: ENC[AES256_GCM,data:PMOJWwAPjL5MrYLIhiF8eUl1zRGLR7CjgGt+NmTReT1HU3tJo6xxN6kJGVOnjc+cSYTh8XgMkpp/dY4RLqBIy1YM/6aag9ZB1isP2ARH607HWahpmLpxcik7wtXtm7x1rk7+q/ay/K5zULIGJbGlSiFm++5oe0ScFEaRM521sFw=,iv:3JcFcAEpCAB+m/nFuibuGPNmKAusETBkpp8QnXSqYzQ=,tag:Dsig5Ga9kys/+Qu9pPH6YA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
