apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: datastore
    labels:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: security
stringData:
    AWS_SECRET_ACCESS_ID: ENC[AES256_GCM,data:PHiQRg==,iv:1zojoEe+8e1w8cuw+wwhYj9bAPi068O8MQAKGs/B+ok=,tag:mCbqRt205RxZvx6TfKfvqQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:n9EVhZM+Tnm3hv7+an/IRHjuNnRigtC8CEtzVaPUm3fWEgWDJu0h6Q==,iv:1JI9ml+xLlN8LYHsahDhSx3stBhur6OjTWy0LwNmvGo=,tag:mw2wcrcjVPvRCc1kiHu8Ug==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/moonlit-watch-362206/locations/global/keyRings/davishaus-keyring/cryptoKeys/sops
          created_at: "2023-06-15T21:16:46Z"
          enc: CiQA3rJLN6yaOwUgzdGqvnZPOyCs080jgMrkd0UamTKxsFS811wSSADC/xGZxa73jdT8yHR/4QB4bwPQ9f0HR78tLLB9CnY+gRv0WYXxDjKaVlZcWXGJas7/wpV+ljiLXlEL1W8AmWTzGT80Fwrtlg==
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jhlwc2kz4rm95t7hfvrj0mhdg7fwmepj90ap5y26ypxf808xmv8qmhnla5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4eGJ0cjZXQUIrem44V1pN
            VHVzYUVuc0gyL2lvZDQzY0lLOWpGY001Y1VRCmVVeXlUMUVabllReFVZQnI5SVc3
            NHhwaURnSVczTU5wQ2VLaThCdDdkd1EKLS0tIHdLNW1OdUR0UDFKcGg2RS9VckRa
            cnZrWXVpc09GeGpkSnA1Z1oyZHpwb1kKydse0GmC+KIG8LTn+eWioFu+tng1F4eS
            k6Ku6JtkhlNSnB6T409p4EtpMcIOegAv6ZVUK8QoLgXsF59qIwDptg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-15T22:40:51Z"
    mac: ENC[AES256_GCM,data:H1l+b517AaXbwAQFkPnf8fWeDEjeEoqbMpz/hl1bESlEYZYGyz6pW1bl7VGMDf/oEk2gmhWNzVNES3TO/eQjN33x8HuBRUenzzYFNISC+W7KwGNwApKnxB9GlpVUj6agqoR5ex8LUaE5Fou1yE8c8MZs6qLvxVj0TmSkoxaJwSQ=,iv:cQ773u+YqyLy0RCYForMTWRMOeadkuLctIsfenvVKfY=,tag:SoZV2FgQ9aagSxF5dfRqBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
